# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Mashirl"

[social.params]
icon = "brand-github"

# [[social]]
# identifier = "mail"
# name = "E-Mail"
# url = "mail:i@mashirl.com"

# [social.params]
# icon = "brand-mail"

#[[social]]
#identifier = "bilibili"
#name = "BiliBili"
#url = "https://space.bilibili.com"

#[social.params]
#icon = "brand-bilibili"